#+Title:   My use-package configuration in org-mode
#+Author:  Felix Brilej
#+STARTUP: showall

* Initialization
  I set some general CoLor variables with the CL and i try to stick to these throughout this
  document whenever i redefine colors. I consider this my standard-library of "good colors" that i
  should use as my kind of color-palette when i go around and change defaults.

  #+BEGIN_SRC emacs-lisp
    (require 'use-package)
    ;; (setq debug-on-error t) (turn on if needed)

    (setq cl-selection-background "ivory1")
    (setq cl-selection-foreground "gray5")

    (setq cl-headline "ghost white")
    (setq cl-first-level "royal blue")
    (setq cl-second-level "IndianRed3")
    (setq cl-third-level "SlateBlue3")
    ;; alternative for sunny days
    ;; (setq cl-third-level "SkyBlue1")
    (setq cl-meta-information-one "cornflower blue")
  #+END_SRC

* File-browsing and text-searching

** Recentf
  I hate browsing for files (I frequently use), this package is supposed to help me out with that
  #+BEGIN_SRC emacs-lisp
    (use-package recentf
      ;; i think it's build-in anyways but I'll just throw config at this problem until it is resolved
      :ensure t
      :config
      ;; Quote: When using TrampMode with recentf.el, it’s advisable to turn off the cleanup feature
      ;; of recentf that attempts to stat all the files and remove them from the recently accessed
      ;; list if they are readable. Tramp means that this requires recentf to open up a remote site
      ;; which will block your emacs process at the most inopportune times.
      ;;
      (setq recentf-auto-cleanup 'never)
      (recentf-mode 1)
      (setq recentf-max-saved-items 50)
      ;; get rid of `find-file-read-only' and replace it with something more useful.
      (global-set-key (kbd "C-x C-r") 'ido-recentf-open)
      (defun ido-recentf-open ()
        "Use `ido-completing-read' to \\[find-file] a recent file"
        (interactive)
        (if (find-file (ido-completing-read "Find recent file: " recentf-list))
            (message "Opening file...")
          (message "Aborting")))
      )
  #+END_SRC

** Helm
  A convenient interface to select about anything from a list: Browse files, select themes, show
  and select search-results and much more.

  Helm-mini is a revolution to navigating through buffers!
  #+BEGIN_SRC emacs-lisp
(use-package helm
  :ensure t
  :init
  (define-key global-map "\C-xb" 'helm-mini)
  :config
  (setq helm-mini-default-sources '(helm-source-buffers-list
				    helm-source-recentf
				    helm-source-bookmarks
				    helm-source-buffer-not-found))
  (helm-mode 1)
  (set-face-attribute 'helm-selection nil
                    :background cl-selection-background
                    :foreground cl-selection-foreground)
  (global-set-key (kbd "M-x") 'helm-M-x)
  (define-key global-map "\C-c\C-s" 'helm-grep-do-git-grep)
  ;; automatically resize the search window based on results (feels convenient)
  (helm-autoresize-mode 1)
  )
  #+END_SRC

** Direx
  An attempt to get a folder-view using [F12], the popwin package is simply a dependancy for that.
  Also this makes the pre-packaged dired display status colors according to the git status of the
  files, which is really cool.
  #+BEGIN_SRC emacs-lisp
(use-package dired-k
  :ensure t
  :config
  (define-key dired-mode-map (kbd "K") 'dired-k)
  ;; You can use dired-k alternative to revert-buffer
  (define-key dired-mode-map (kbd "g") 'dired-k)
  ;; always execute dired-k when dired buffer is opened
  (add-hook 'dired-initial-position-hook 'dired-k)
  (add-hook 'dired-after-readin-hook #'dired-k-no-revert)
  )

;; Makes small windows possible intended to be closed again soon
;; required by direx
(use-package popwin
  :ensure t
  :config
  (popwin-mode 1)
  )

(use-package direx
  :ensure t
  :config
  (push '(direx:direx-mode :position left :width 25 :dedicated t)
      popwin:special-display-config)
  (global-set-key [f12] 'direx:jump-to-directory-other-window)
  )
  #+END_SRC

*** TODO Fix the error I get on every emacs startup because of this

** Finding files
   As great as helm is, there is an even better file-finding package, however it hinders me from
   remote file editing, for which i then manually have to call "find-file", which is an inconvenience.
   #+BEGIN_SRC emacs-lisp
(use-package counsel
  :ensure t
  :config
  (require 'swiper)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  )
   #+END_SRC

*** TODO Make this more convenient
    Ideas:
    - Try the helm function again with better customization so it is convenient
    - Customize this open more so it does enable me to edit remote-files

** Searching for strings
  Deft searches for strings in my org-files, at work this takes forever to load though, so it is
  not a core part of my workflow. I might have to adapt to only search through text-files.
  #+BEGIN_SRC emacs-elisp
;; documentation over here: http://jblevins.org/projects/deft/
(use-package deft
  :ensure t ;;doesnt work on work pc (sometimes), unable to install from melpa
  :config
  (setq deft-extensions '("txt" "tex" "org"))
  (if (equal "work" (getenv "SYSENV"))
      (progn (setq deft-directory (concat "C:\\Users\\" (getenv "USERNAME") "\\Desktop\\Projekte")))
      )
  (if (or (equal "home" (getenv "SYSENV"))
          (equal "laptop" (getenv "SYSENV"))
          (equal "linux-vm" (getenv "SYSENV")))
      (progn )
    )
  (setq deft-directory "~/Dropbox/org")
  (setq deft-recursive t)
  (setq deft-use-filename-as-title t)
  (global-set-key [f10] 'deft)
  )
  #+END_SRC

  This package searches for strings in the current textfile very conveniently since it gives you
  a quick overview over *all* of the search-results.
  This package however frequently breaks on windows, such that suddenly i can only scroll down in
  the result-list. Reinstalling the package fixes that, however that is a huge inconvenience.
  #+BEGIN_SRC emacs-lisp
(use-package swiper-helm
  :ensure t
  :config
  (global-set-key (kbd "C-s") 'swiper-helm)
  (global-set-key (kbd "C-c u") 'swiper-all)
  )
  #+END_SRC

** Open the explorer
   To open the OS-specific file-browser either use this command: =M-! explorer .= or the following
   code snippet:
   #+BEGIN_SRC emacs-lisp
   (defun browse-current-folder ()
     "open the current buffer’s folder"
     (interactive)
     (browse-url (concat "file://" (file-name-directory (buffer-file-name))))
   )
   (global-set-key [M-f9] 'browse-current-folder)
   #+END_SRC

* Conveniences

** Undo-tree
   #+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :ensure t
  :config
  (global-undo-tree-mode)
  )
   #+END_SRC

** Which-key
   My guide for shortcuts i forget in part and for exploring options after already having pressed
   parts of a key-combination.
   #+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :config
  (which-key-setup-side-window-right)
  (setq which-key-popup-type 'side-window)
  (which-key-mode)
  )
    #+END_SRC

** Immortal-scratch
   Respawns the scratch buffer when its killed, feels just right
   #+BEGIN_SRC emacs-lisp
(use-package immortal-scratch
  :ensure t
  :config
  (immortal-scratch-mode t)
  )
   #+END_SRC

** Yasnippet
   #+BEGIN_SRC emacs-lisp
;; Currently there is a problem "package does not untar cleanly"
(use-package yasnippet
  :ensure nil
  :init
  (define-key global-map "\C-cy" 'yas/insert-snippet)
  ;;(setq yas-snippet-dirs (append yas-snippet-dirs
  ;;"~/.emacs.d/elpa/yasnippet-20150912.1330/snippets/"))
  :config
  (yas-global-mode 1)
  )
   #+END_SRC

** Smooth-scrolling
   This mode doesnt have a good interaction with C-l which centers the current line in the buffer
   to the middle, top and bottom. Using C-l to put the current line to the top of the buffer and
   then pressing UP results in an unpleasant shift of the buffer position. However for simple
   scrolling this is nice.
   #+BEGIN_SRC emacs-lisp
(use-package smooth-scrolling
  :ensure t
  :init
  (add-hook 'org-mode-hook (lambda () (smooth-scrolling-mode 1)))
  )
   #+END_SRC

** Smartparens
   This package is sometimes not so smart, sometimes it inserts parenthesis when i dont want them,
   especially in org-mode. I need to customize this more.
   #+BEGIN_SRC emacs-lisp
;; smartparens, a mode that tries to be smart around parentheses of all kinds
(use-package smartparens
  :ensure t
  :init
  (smartparens-global-mode t)
  ;; make the overlay disappear
  (custom-set-faces '(sp-pair-overlay-face ((t nil))))
  )
   #+END_SRC

** Rainbow delimiters
   This package is kind of a useless extension since the colors it uses are way too subtle
   #+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :init
  (add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)
  )
   #+END_SRC
** Emoji-autocomplete (company-emoji)
   #+BEGIN_SRC emacs-lisp
;; If i dont uncomment this this attempts to get installed at work?!? TODO
;; I bet its the new use-package config i took from sachac's config
;; Settings for company plus company-emoji
(use-package company-emoji
  :if (equal "laptop" (getenv "SYSENV"))
  :init
  (require 'color)
  (let ((bg (face-attribute 'default :background)))
    (custom-set-faces
     `(company-tooltip ((t (:inherit default :background ,(color-lighten-name bg 2)))))
     `(company-scrollbar-bg ((t (:background ,(color-lighten-name bg 10)))))
     `(company-scrollbar-fg ((t (:background ,(color-lighten-name bg 5)))))
     `(company-tooltip-selection ((t (:inherit font-lock-function-name-face))))
     `(company-tooltip-common ((t (:inherit font-lock-constant-face))))))
  )
   #+END_SRC

** Copy-clipboard hack
   Save whatever’s in the current (system) clipboard before replacing it with the Emacs’ text.

   More tricks like this: https://github.com/dakrone/eos/blob/master/eos.org
   #+BEGIN_SRC emacs-lisp
(setq save-interprogram-paste-before-kill t)
   #+END_SRC

* The big guns

** Magit
   On some systems the "GIT_ASKPASS" variable i set leads to a nice GUI for entering usename on
   passwords, on other systems i get an ugly error-message everytime i "git push". This is open
   for improvement but not a big issue.
   #+BEGIN_SRC emacs-lisp
;; The Windows User-Home needs to be in some kind of path such that magit finds the .gitconfig
(use-package magit
  :if (cond ((equal "home" (getenv "SYSENV")) (message "Loading magit"))
      ((equal "laptop" (getenv "SYSENV")) (message "Loading magit"))
      ((equal "work" (getenv "SYSENV")) (message "Loading magit"))
      )
  :ensure t
  :config
  (add-to-list 'exec-path "C:/Program Files/Git/bin")
  (define-key global-map (kbd "C-c m") 'magit-status)
  (setenv "GIT_ASKPASS" "git-gui--askpass")
  )
   #+END_SRC

*** TODO Warn if username and useremail are not set

*** Define emacs shutdown function (taken from baron42bba)
    Emacs is a powerfull tool, so powerfull that i need to protect myself from deleting huge
    chunks of my org-files on accident without noticing. I can do this by committing after each
    day of work, so if i find out today that recently i must have deleted some part of my org-file
    i can go back into the file-history to bring it back. The emacs backup-files dont help in this
    scenario.

    #+BEGIN_SRC emacs-lisp :tangle no
  ;; define function to shutdown emacs server instance
  (defun server-shutdown ()
    "Save buffers, Quit, and Shutdown (kill) server"
    (interactive)
    (save-some-buffers)
    (shell-command "git --work-tree ~/org/ --git-dir ~/org/.git commit -a -m 'autocommit'")
    (shell-command "git --work-tree ~/org/ --git-dir ~/org/.git push origin")
    (if (equal "work" (getenv "SYSENV"))
        (progn
          (shell-command "git --work-tree ~/workorg/ --git-dir ~/workorg/.git commit -a -m 'autocommit'")
          (shell-command "git --work-tree ~/workorg/ --git-dir ~/workorg/.git push origin")
          ))
    (setq twittering-cert-file nil)
    (kill-emacs)
    )
    #+END_SRC

**** TODO Make sure that i actually have a server running
     smirk

** Org-mode
   #+BEGIN_SRC emacs-lisp
(use-package org
  :ensure t
  :config
  (setq org-export-coding-system 'utf-8-unix)
  (setq org-export-with-clocks t)
  (setq org-export-preserve-breaks t)
  (setq org-agenda-start-with-clockreport-mode t)
  ;; Org Babel
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
	 (lisp . t)
	 (sh . t)
	 (perl . t)
	 (dot . t) ;; activates graphviz dot support
	 ))
  ;; Remove ^M Errors in Babel
  (add-to-list 'process-coding-system-alist
               '("bash" . (undecided-unix)))
  (add-hook 'comint-output-filter-functions
            'comint-strip-ctrl-m)
  ;; Send stderror into the result drawer instead of an extra window
  (setq org-babel-default-header-args:sh
        '((:prologue . "exec 2>&1") (:epilogue . ":"))
        )
  ;; Custom Keybindings
  (fset 'fbr/convert-listitem-into-checklistitem
        "\355\C-f\C-f[]\C-f\C-b \C-b\C-b \C-a\C-n")
  (global-set-key (kbd "C-c b") 'fbr/convert-listitem-into-checklistitem)
  (defun fbr/org-agenda-reduce-to-current-file()
      (interactive)
      (setq org-agenda-files (list (buffer-file-name)))
      )
  ;; Custom commands
  (define-key global-map "\C-cl" 'org-store-link)
  (define-key global-map "\C-ca" 'org-agenda)
  (define-key global-map "\C-cc" 'org-capture)
  (define-key global-map "\M-n" 'org-metadown)
  (define-key global-map "\M-p" 'org-metaup)
  (define-key org-mode-map "\C-m" 'nil)
  (define-key org-mode-map (kbd "<f5>") 'org-babel-execute-src-block)
  (global-set-key (kbd "<f9>") 'org-todo)
  ;; Load syntax-highlighting for source-blocks
  (setq org-src-fontify-natively t)
  ;; log the time when a task is "done"
  (setq org-log-done t)
  ;; put "CLOCK" times into a drawer
  (setq org-log-into-drawer t)
  ;; makes sure LOGBOOK and PROPERTIES go first
  (setq org-log-state-notes-insert-after-drawers t)
  (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
  ;; add archived tasks to the agenda and clocktable, otherwise they dont show up
  (setq org-agenda-archives-mode t)
  ;; Visual modifications
  ;; Strike through DONE headlines
  (setq org-fontify-done-headline t)
  ;; autofill hooks for automatic indentation
  (add-hook 'change-log-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
  (setq auto-hscroll-mode nil)
  (setq org-hide-emphasis-markers t)
  (setq org-tags-column -70)
  ;; to aligh the tags that already exist simple execute "org-align-all-tags" on the file
  ;; change from ... to the arrow
  (setq org-ellipsis "⤵")
  ;; Circulate Bullets instead of asteriks
  (font-lock-add-keywords 'org-mode
                          '(("^ +\\([-*]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
  ;; what does this even do?
  (setq org-export-with-sub-superscripts nil)
  ;; remove the "validate"-link from the org-html export
  (setq org-export-html-validation-link nil)
  (setq org-tags-match-list-sublevels 'indented)
  ;; A package to visualize repeated tasks in the org agenda
  (require 'org-habit)
  (add-to-list 'org-modules 'org-habit)
  (setq org-habit-show-habits-only-for-today nil)
  )
   #+END_SRC

   The faulty code that allows me to have those super-cool appointment-reminders.
   #+BEGIN_SRC emacs-lisp :tangle no
       ;; Make appt aware of appointments from the agenda
     ;;  (defun fbr/org-agenda-to-appt ()
     ;;    "Activate appointments found in `org-agenda-files'."
     ;;    (interactive)
     ;;    (require 'org)
     ;;    (let* ((today (org-date-to-gregorian
     ;;                   (time-to-days (current-time))))
     ;;           (files org-agenda-files) entries file)
     ;;      (while (setq file (pop files))
     ;;        (setq entries (append entries (org-agenda-get-day-entries
     ;;                                       file today :timestamp))))
     ;;      (setq entries (delq nil entries))
     ;;      (mapc (lambda(x)
     ;;              (let* ((event (org-trim (get-text-property 1 'txt x)))
     ;;                     (time-of-day (get-text-property 1 'time-of-day x)) tod)
     ;;                (when time-of-day
     ;;                  (setq tod (number-to-string time-of-day)
     ;;                        tod (when (string-match
     ;;                                   "\\([0-9]\\{1,2\\}\\)\\([0-9]\\{2\\}\\)" tod)
     ;;                              (concat (match-string 1 tod) ":"
     ;;                                      (match-string 2 tod))))
     ;;                  (if tod (appt-add tod event))))) entries)))
     ;;  (defadvice fbr/org-agenda-to-appt (before wickedcool activate)
     ;;    "Clear the appt-time-msg-list."
     ;;    (setq appt-time-msg-list nil))
     ;;  (org-agenda-to-appt)
   #+END_SRC

*** TODO Fix the error that comes on startup
    The "appt-add" function i use for the appointment-mode causes this error, i copied the code
    from somewhere.

    Isolated the code..

*** Latex-settings
    #+BEGIN_SRC emacs-lisp
   ;; Latex settings (somehow doesn't work if i put it in usepackage definition of org)
   (require 'ox-latex)
   (add-to-list 'org-latex-classes
                '("bjmarticle"
                  "\\documentclass{article}
                   \\usepackage[utf8]{inputenc}
                   \\usepackage[T1]{fontenc}
                   \\usepackage{graphicx}
                   \\usepackage{longtable}
                   \\usepackage{hyperref}
                   \\usepackage{natbib}
                   \\usepackage{amssymb}
                   \\usepackage{amsmath}
                   \\usepackage{geometry}
                   \\geometry{a4paper,left=2.5cm,top=2cm,right=2.5cm,bottom=2cm,marginparsep=7pt, marginparwidth=.6in}"
                  ("\\section{%s}" . "\\section*{%s}")
                  ("\\subsection{%s}" . "\\subsection*{%s}")
                  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                  ("\\paragraph{%s}" . "\\paragraph*{%s}")
                  ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
                )
    #+END_SRC
*** Org-mode ox-latex extension
   Exports clock-data to csv which is a useful data-format for generating graphs! Im not far into
   this topic though.
   #+BEGIN_SRC emacs-lisp
(use-package org-clock-csv
  :ensure t
  )
   #+END_SRC
*** Org-mode openwith extension
    Open pdfs with an external pdf-viewer to get a good resolution (Only use this for my laptop,
    needs to be fixed for my windows PC if i ever use it for them).
    #+BEGIN_SRC emacs-lisp
(use-package openwith
  :ensure t
  :config
  (setq openwith-associations '(("\\.pdf\\'" "evince" (file))))
  (openwith-mode t)
)
   #+END_SRC

*** Orgmode calendar extension
   #+BEGIN_SRC emacs-lisp
(use-package calfw
  :ensure t
  :config
  (require 'calfw-org)
  (setq cfw:org-overwrite-default-keybinding t)
  )
   #+END_SRC

*** Orgmode alert extension
   This is a package on top of the original =alert.el=

   Im pretty sure this makes my "fbr/tea-timer" possible which is defined somewhere else. This way
   i can basically remind myself to not spend too much time on a task by setting a timer
   before-hand. This can also be done with "C-c C-x C-e" after clocking into a task. This way an
   expected time-consumption can be set and the timer gets red once we exceed this time, which is
   not as convenient as having an extra alert-window in my oppinion.

   For windows i have found a small programm that can simply display notifications =notifu.exe=
   which is included in this repository, but i havent found a way yet of implementing this. The
   following code only works for my linux-laptop
   #+BEGIN_SRC emacs-lisp
(use-package org-alert
  :ensure t
  :init
  ;; set this option from alert.el to make alerts visual
  (setq alert-default-style 'libnotify)
  (setq org-alert-enable t)
  (setq org-alert-interval 60)
  )
   #+END_SRC

*** Orgmode htmlize extension
   Inserts highlighting of Org Source-Blocks on Html-Export
   #+BEGIN_SRC emacs-lisp
(use-package htmlize
  :ensure t
  )
   #+END_SRC

** Tramp
   #+BEGIN_SRC emacs-lisp
     (use-package tramp
       :ensure t
       :init
       (setq tramp-verbose 5)
       ;; sshx is the required for cygwin
       (setq default-tramp-method "sshx")
       ;; Fix for base64 error
       ;; see footnotes here: http://www.howardism.org/Technical/Emacs/literate-devops.html
       ;; you can try this:
       ;;(setq tramp-remote-coding-commands '(b64 "base64" "base64 -d -i"))
       ;; When connecting to a remote server it usually does source the profile, but for some
       ;; reason doesn't do that for $PATH by default. You'll have to specifically tell tramp
       ;; to do that from your .emacs. with
       (add-to-list 'tramp-remote-path 'tramp-own-remote-path)
       :config
       (define-minor-mode sensitive-mode
             "For sensitive files like password lists.
                     It disables backup creation and auto saving.

                     With no argument, this command toggles the mode.
                     Non-null prefix argument turns on the mode.
                     Null prefix argument turns off the mode."
             ;; The initial value.
             nil
             ;; The indicator for the mode line.
             " Sensitive"
             ;; The minor mode bindings.
             nil
             (if (symbol-value sensitive-mode)
                     (progn
                       ;; disable backups
                       (set (make-local-variable 'backup-inhibited) t)
                       ;; disable auto-save
                       (if auto-save-default
                               (auto-save-mode -1)))
             ;; resort to default value of backup-inhibited
               (kill-local-variable 'backup-inhibited)
             ;; resort to default auto save setting
               (if auto-save-default
                   (auto-save-mode 1))))
       ;; from howards blog: http://www.howardism.org/Technical/Emacs/literate-devops.html this is
       ;; supposed to overwrite the standard org-mode function in ob-core.el which is buggy and can
       ;; completely block the org-babel functinality on windows.
       ;;
       ;; On windows the faulty file is here: <path_to_emacs>\emacs\share\emacs\24.5\lisp\org
       (defun org-babel-temp-file (prefix &optional suffix)
       "Create a temporary file in the `org-babel-temporary-directory'.
     Passes PREFIX and SUFFIX directly to `make-temp-file' with the
     value of `temporary-file-directory' temporarily set to the value
     of `org-babel-temporary-directory'."
       (if (file-remote-p default-directory)
           (let ((prefix
                  ;; We cannot use `temporary-file-directory' as local part
                  ;; on the remote host, because it might be another OS
                  ;; there.  So we assume "/tmp", which ought to exist on
                  ;; relevant architectures.
                  (concat (file-remote-p default-directory)
                          ;; REPLACE temporary-file-directory with /tmp:
                          (expand-file-name prefix "/tmp/"))))
             (make-temp-file prefix nil suffix))
         (let ((temporary-file-directory
                (or (and (boundp 'org-babel-temporary-directory)
                         (file-exists-p org-babel-temporary-directory)
                         org-babel-temporary-directory)
                    temporary-file-directory)))
           (make-temp-file prefix nil suffix))))
       )
   #+END_SRC

* Programming
  I rarely use emacs an IDE, so this is not a rich section.

** C Lang
  The main thing i use from the following is the "jump to definition" function, which is otherwise
  a tedious manual task.
  #+BEGIN_SRC emacs-lisp
(use-package helm-gtags
  :if (equal "laptop" (getenv "SYSENV"))
  :config
  ;; Enable helm-gtags-mode
  (add-hook 'dired-mode-hook 'helm-gtags-mode)
  (add-hook 'eshell-mode-hook 'helm-gtags-mode)
  (add-hook 'c-mode-hook 'helm-gtags-mode)
  (add-hook 'c++-mode-hook 'helm-gtags-mode)
  (add-hook 'asm-mode-hook 'helm-gtags-mode)

  (define-key helm-gtags-mode-map (kbd "C-c g a") 'helm-gtags-tags-in-this-function)
  (define-key helm-gtags-mode-map (kbd "C-j") 'helm-gtags-select)
  (define-key helm-gtags-mode-map (kbd "M-.") 'helm-gtags-dwim)
  (define-key helm-gtags-mode-map (kbd "M-,") 'helm-gtags-pop-stack)
  (define-key helm-gtags-mode-map (kbd "C-c <") 'helm-gtags-previous-history)
  (define-key helm-gtags-mode-map (kbd "C-c >") 'helm-gtags-next-history)

  (setq-local imenu-create-index-function #'ggtags-build-imenu-index)
  )
  #+END_SRC
* Themes
  This section should be add the end, since some of the modes come with their own color-settings
  and these are supposed to be overwritten by the theme-config, the theme-config should have the
  final say in coloring, so I can appreciate the themes in all their beauty.

  Themes usually dont touch the helm-interface, for that there is a package called "helm-themes"
  and it usually makes sense to load the helm-theme along with the "main" theme.

** Seti theme
   I used this theme for a long time and it is pretty good, but sometimes i have to mix it up!
   #+BEGIN_SRC emacs-lisp
;; (use-package seti-theme
;;   :ensure t
;;   :config
;;   (custom-set-faces
;;    '(font-lock-function-name-face ((t (:foreground "royal blue"))))
;;    '(font-lock-comment-face ((t (:foreground "light sea green")))) ;9FCA56
;;    '(helm-source-header ((t (:background "gray14" :foreground "white" :weight bold :height 1.3 :family "Sans Serif"))))
;;    `(helm-candidate-number ((t (:foreground ,cl-meta-information-one))))
;;    ;;'(helm-candidate-number ((t (:foreground "goldenrod2"))))
;;    `(helm-selection ((t (:background ,cl-selection-background :foreground ,cl-selection-foreground))))
;;    ;;'(helm-selection ((t (:background "light gray" :foreground "gray5"))))
;;    ;; added the outline definitions to blindly work towards a global color theme
;;    ;; which variables inherit from these "outline" variables?
;;    `(org-level-1 ((t (:inherit org-level-1 :foreground ,cl-first-level))))
;;    `(outline-2 ((t (:foreground ,cl-second-level))))
;;    `(outline-3 ((t (:foreground ,cl-third-level))))
;;    `(org-document-title ((t (:foreground ,cl-headline :weight bold :height 1.44))))
;;    `(org-headline-done ((((class color) (min-colors 16) (background dark)) (:strike-through t))))
;;    `(org-date ((t (:foreground ,cl-meta-information-one :underline t))))
;;    `(org-link ((t (:inherit nil :foreground ,cl-meta-information-one))))
;;    ;; Color the Org-Blocks beautifully for color schemes that do not do that
;;    `(org-block-foreground ((t (:foreground "dark orange"))))
;;    `(org-block-begin-line ((t (:foreground "SlateBlue4"))))
;;    `(org-block-end-line ((t (:foreground "SlateBlue4"))))
;;    `(org-document-info ((t (:foreground "medium sea green"))))
;;    `(org-document-info-keyword ((t (:foreground "light sea green"))))
;;    )
;;   (set-background-color "grey12")
;;   )
   #+END_SRC
** Other unused themes
   #+BEGIN_SRC emacs-lisp
;; (use-package dark-mint-theme
;;   :ensure t
;;   :config
;;   (load-theme 'dark-mint t)
;;   )

;; (use-package twilight-bright-theme
;;   :ensure t
;;   :config
;;   (load-theme 'twilight-bright t)
;;   )

;; temporary disabled
;; (use-package oceanic-theme
;;   :ensure t
;;   :config
;;   (load-theme 'oceanic t)
;;   )
   #+END_SRC

** Org-mode Size settings
   Regardless of the theme i got used to having the org-headlines at certain sizes.
   #+BEGIN_SRC emacs-lisp
;; Org-mode Size-Customizations
(custom-set-faces
 `(org-level-1 ((t (:inherit outline-1 :height 1.4))))
 `(org-level-2 ((t (:inherit outline-2 :height 1.3))))
 `(org-level-3 ((t (:inherit outline-3 :height 1.2))))
 `(org-level-4 ((t (:inherit outline-4 :height 1.1))))
 )
   #+END_SRC
** Purple-haze theme
   This theme is great, some of the monitors i use however dont display the slight
   color-differences between the different tones of purple nicely, such that it just looks
   black. Playing with the monitor-settings sadly doesnt resolve this, this might not be my final
   theme. "Final theme".. *smirk*

   #+BEGIN_SRC emacs-lisp
(use-package purple-haze-theme
  :ensure t
  :config
  (load-theme 'purple-haze t)
  )

(use-package helm-themes
  :ensure t
  :config
  (helm-themes--load-theme "purple-haze")
  )
   #+END_SRC
* Modeline
  I never learned how to successfully edit the modeline yet, i just keep copying configs from nice
  screenshots which then only work in part so i have to delete them again lol. Some themes come
  with okay modeline configurations

  #+BEGIN_SRC emacs-lisp
;; The mode-line
;; load it after the theme since themes sometimes set their own mode-line
;; former problem: use-package doesnt find spaceline-config or spaceline
;; doest it still exist?
;; (use-package spaceline-config
;;   :ensure spaceline
;;   :config
;;   (spaceline-emacs-theme)
;;   (spaceline-helm-mode)
;;   (spaceline-toggle-buffer-size-off)
;;   (spaceline-toggle-nyan-cat-on)
;;   (spaceline-toggle-minor-modes-off)
;;   (spaceline-toggle-buffer-position-off)
;;   (custom-set-faces
;;    '(spaceline-highlight-face ((t (:inherit 'mode-line :foreground "#3E3D31" :background "SeaGreen3"))))
;;    '(spaceline-modified ((t (:inherit 'mode-line :foreground "#3E3D31" :background "SeaGreen3"))))
;;    '(spaceline-unmodified ((t (:inherit 'mode-line :foreground "#3E3D31" :background "SeaGreen3"))))
;;    '(spaceline-unmodified-p ((t (:inherit 'mode-line :foreground "#3E3D31" :background "SeaGreen3"))))
;;    ;; LightGoldenrod ist die Farbe vom Helm-buffer, nur was ist das Face?
;;    )
;;   (spaceline-highlight-face-default)
;;   (spaceline-highlight-face-modified)
;;   )

;; Sadly results in flickering on my laptop and doesnt install relyably on my windows-pc
;; (use-package nyan-mode
;;   :ensure t
;;   :config
;;   (nyan-mode 1)
;;   (nyan-start-animation)
;;   )
  #+END_SRC
