* If you are new here
  This config is highly customized and no good for a beginner. Even for emacs users this config is
  probably only interesting in specific points they can then copy to their own config. However
  along the way I found some nice tutorials on emacs in general which I'd like to point out:
  - https://www.inkandben.com/org-mode-resources for a nice collection of tutorials
  - http://emacs.sexy/ a well done advertisement-like site on emacs
  - https://emacsthemes.com/
  - https://github.com/emacs-tw/awesome-emacs

* About this repository
  Started to maintain my emacs-config here on github when I noticed there were more than a handful
  of things I wanted to configure about emacs, and it was too annoying to set them each time by
  hand when switching the environment.

  🏆 Things I am proud to have accomplished since my first commit here:
  - I use "use-package" for automatic package installation.
  - My config-files are written in org-mode
  - The different environments I work with emacs in are typed (work / home / laptop /
    uni). Depending on the environment I load different packages. I tell emacs which environment I
    am in by setting the system variable "SYSENV".
  - The overall file-structure is not a mess

  🌵 Things I struggle with:
  - Minor things about my typescript and rust setup
  - Having great keybindings for all situations (my navigation could be better)
  - Keeping all my org configuration consistent

** The structure of these config files
   - init.el :: bootstraps the initialization through org-mode
   - my-stock-changes.org :: customizes the default emacs behaviour
   - my-org-usepackages.org :: adds and customizes packages
   - elisp-goodies.el :: some of my custom functions and work-in-progress

** Research enabled by this config
   I wrote my bachelor-thesis with this config. In order to do that I needed to extend my org-mode
   config extensively. An alternative to this would be downloading an emacs distribution / config
   that is designed just for writing scientifical papers, like [[https://github.com/jkitchin/scimax][Scimax]].

   Configuration that specifically enables me to do that is tagged with "research". On linux i had
   to install packages ontop of simple configuration inside emacs:
   #+BEGIN_SRC sh
   sudo apt-get install ess
   sudo apt-get install texlive #required for pdf rendering (and more?)
   sudo apt-get install texlive-latex-extra #stop the pdf-export from failing due to missing package "wrapfig.sty"
   sudo apt-get install r-base #enables the creation of graphs from emacs
   #+END_SRC

   For Windows these additional steps are required to make the pdf export work:
   - Download "pdflatex" from here: https://miktex.org/download
     - Latex Live is an alternative
   - Update its packages using the miktex update manager
   - Install the wrapfig package
   - Install the url package
   - Add the binary directory of miktex to the environment variables and restart emacs
   - Try the export!
